import type { PublicInspectorRecord } from "./types";

type SurfaceNode = PublicInspectorRecord & {
  id: string;
  name: string;
  color: "cyan" | "emerald" | "blue" | "amber" | "rose" | "violet";
  position: "center" | "upper-left" | "upper-right" | "lower-left" | "lower-right" | "bottom";
};

export const surfaceNodes = [
  {
    id: "core-hub",
    name: "CORE-HUB",
    nodeId: "core-hub",
    publicName: "CORE-HUB",
    nodeType: "surface",
    exposureState: "static",
    authorityLayer: "governance-plane",
    summary: "Coordinates review boundaries and public routing posture.",
    functionSummary: "Visual orientation, lane routing, and boundary visibility.",
    authoritySummary: "Static explanatory model only. No runtime execution claim.",
    relations: [{ label: "Routes", target: "public lanes", direction: "downstream" }],
    evidenceKind: "conceptual",
    ctaMode: "none",
    color: "cyan",
    position: "center",
  },
  {
    id: "theia",
    name: "Theia",
    nodeId: "theia",
    publicName: "Theia",
    nodeType: "agent",
    exposureState: "static",
    authorityLayer: "human-review",
    summary: "Represents coherence, continuity, and declared-context awareness.",
    functionSummary: "Public explanation of integration and drift awareness.",
    authoritySummary: "No hidden inference or private-state claim.",
    relations: [{ label: "Integrates", target: "reviewed context", direction: "related" }],
    evidenceKind: "conceptual",
    ctaMode: "none",
    color: "emerald",
    position: "upper-left",
  },
  {
    id: "thoth",
    name: "Thoth",
    nodeId: "thoth",
    publicName: "Thoth",
    nodeType: "agent",
    exposureState: "static",
    authorityLayer: "human-review",
    summary: "Represents evidence discipline and source-grounded review.",
    functionSummary: "Public explanation of validation posture.",
    authoritySummary: "No certification or compliance guarantee.",
    relations: [{ label: "Validates", target: "evidence posture", direction: "related" }],
    evidenceKind: "conceptual",
    ctaMode: "none",
    color: "blue",
    position: "upper-right",
  },
  {
    id: "merlin",
    name: "Merlin",
    nodeId: "merlin",
    publicName: "Merlin",
    nodeType: "agent",
    exposureState: "static",
    authorityLayer: "human-review",
    summary: "Represents ordered planning and review-aware task sequencing.",
    functionSummary: "Public explanation of sequence, not execution.",
    authoritySummary: "Advisory sequence does not equal production authority.",
    relations: [{ label: "Sequences", target: "reviewed work", direction: "downstream" }],
    evidenceKind: "conceptual",
    ctaMode: "none",
    color: "amber",
    position: "lower-left",
  },
  {
    id: "osiris",
    name: "Osiris",
    nodeId: "osiris",
    publicName: "Osiris",
    nodeType: "agent",
    laneAffiliation: "audit",
    exposureState: "reviewed",
    authorityLayer: "human-review",
    summary: "Represents the commercial audit lane and review deliverables.",
    functionSummary: "Intake, structural review, evidence pass, findings, and delivery.",
    authoritySummary: "Findings only. No autonomous remediation.",
    relations: [{ label: "Produces", target: "audit findings", direction: "downstream" }],
    evidenceKind: "reviewed-copy",
    ctaMode: "view-path",
    ctaLabel: "Review audit lane",
    ctaHref: "#audit",
    color: "rose",
    position: "lower-right",
  },
  {
    id: "librarian",
    name: "Librarian",
    nodeId: "librarian",
    publicName: "Librarian",
    nodeType: "agent",
    exposureState: "static",
    authorityLayer: "human-review",
    summary: "Represents artifact placement, retrieval, and source organization.",
    functionSummary: "Public explanation of knowledge placement.",
    authoritySummary: "Retrieval and organization do not imply source alteration.",
    relations: [{ label: "Organizes", target: "source artifacts", direction: "related" }],
    evidenceKind: "conceptual",
    ctaMode: "none",
    color: "violet",
    position: "bottom",
  },
] as const satisfies readonly SurfaceNode[];
