export const surfaceNodes = [
  {
    id: "core-hub",
    name: "CORE-HUB",
    label: "Governance center",
    role: "Coordinates review boundaries and public routing posture.",
    scope: "Visual orientation, lane routing, and boundary visibility.",
    authorityBoundary: "Static explanatory model only. No runtime execution claim.",
    output: "Route clarity and review posture.",
    color: "cyan",
    position: "center",
  },
  {
    id: "theia",
    name: "Theia",
    label: "Integration",
    role: "Represents coherence, continuity, and declared-context awareness.",
    scope: "Public explanation of integration and drift awareness.",
    authorityBoundary: "No hidden inference or private-state claim.",
    output: "Contextual orientation.",
    color: "emerald",
    position: "upper-left",
  },
  {
    id: "thoth",
    name: "Thoth",
    label: "Validation",
    role: "Represents evidence discipline and source-grounded review.",
    scope: "Public explanation of validation posture.",
    authorityBoundary: "No certification or compliance guarantee.",
    output: "Evidence boundary clarity.",
    color: "blue",
    position: "upper-right",
  },
  {
    id: "merlin",
    name: "Merlin",
    label: "Sequencing",
    role: "Represents ordered planning and review-aware task sequencing.",
    scope: "Public explanation of sequence, not execution.",
    authorityBoundary: "Advisory sequence does not equal production authority.",
    output: "Build order clarity.",
    color: "amber",
    position: "lower-left",
  },
  {
    id: "osiris",
    name: "Osiris",
    label: "Audit",
    role: "Represents the commercial audit lane and review deliverables.",
    scope: "Intake, structural review, evidence pass, findings, delivery.",
    authorityBoundary: "Findings only. No autonomous remediation.",
    output: "Audit report and recommendations.",
    color: "rose",
    position: "lower-right",
  },
  {
    id: "librarian",
    name: "Librarian",
    label: "Curation",
    role: "Represents artifact placement, retrieval, and source organization.",
    scope: "Public explanation of knowledge placement.",
    authorityBoundary: "Retrieval and organization do not imply source alteration.",
    output: "Findable context.",
    color: "violet",
    position: "bottom",
  },
] as const;
