import type { PublicInspectorRecord } from "./types";

type SurfaceNode = PublicInspectorRecord & {
  id: string;
  name: string;
  color: "cyan" | "emerald" | "blue" | "amber" | "rose" | "violet";
  position: "center" | "upper-left" | "upper-right" | "lower-left" | "lower-right" | "bottom";
};

export const surfaceNodes = [
  {
    id: "core-hub",
    name: "CORE-HUB",
    nodeId: "core-hub",
    publicName: "CORE-HUB",
    nodeType: "surface",
    exposureState: "reviewed",
    authorityLayer: "governance-plane",
    summary: "Organization-level governance and canonical-governance record for MIRRORNODE.",
    functionSummary: "Preserves governance decisions, canonical sources, review boundaries, and source-linked authority records.",
    authoritySummary: "Governance authority is source- and disposition-bound; runtime capability or file location does not manufacture authority.",
    relations: [{ label: "Governs", target: "organization-level governance", direction: "downstream" }],
    evidenceKind: "reviewed-copy",
    ctaMode: "none",
    color: "cyan",
    position: "center",
  },
  {
    id: "theia",
    name: "Theia",
    nodeId: "theia",
    publicName: "Theia",
    nodeType: "agent",
    exposureState: "reviewed",
    authorityLayer: "human-review",
    summary: "Integrates reviewed context, continuity, and perspectives into a coherent operating picture.",
    functionSummary: "Architectural integration, coherence checking, drift awareness, and cross-lane continuity.",
    authoritySummary: "Integration does not create authority; applicable governance, approval, and security boundaries remain controlling.",
    relations: [{ label: "Integrates", target: "reviewed positions and context", direction: "related" }],
    evidenceKind: "reviewed-copy",
    ctaMode: "none",
    color: "emerald",
    position: "upper-left",
  },
  {
    id: "thoth",
    name: "Thoth",
    nodeId: "thoth",
    publicName: "Thoth",
    nodeType: "agent",
    exposureState: "reviewed",
    authorityLayer: "human-review",
    summary: "Security and authority-boundary review grounded in source and evidence discipline.",
    functionSummary: "Tests escalation paths, provenance, security posture, and fail-closed boundaries.",
    authoritySummary: "Security review constrains unsafe paths but does not itself authorize execution or claim certification.",
    relations: [{ label: "Reviews", target: "security and authority boundaries", direction: "related" }],
    evidenceKind: "reviewed-copy",
    ctaMode: "none",
    color: "blue",
    position: "upper-right",
  },
  {
    id: "merlin",
    name: "Merlin",
    nodeId: "merlin",
    publicName: "Merlin",
    nodeType: "agent",
    exposureState: "reviewed",
    authorityLayer: "human-review",
    summary: "Planning, sequencing, dependency mapping, and orchestration advice.",
    functionSummary: "Advises what should happen next and in what order without dispatching or executing work.",
    authoritySummary: "Advisory sequencing does not grant approval, routing, canon, or execution authority.",
    relations: [{ label: "Sequences", target: "reviewed work", direction: "downstream" }],
    evidenceKind: "reviewed-copy",
    ctaMode: "none",
    color: "amber",
    position: "lower-left",
  },
  {
    id: "osiris",
    name: "Osiris",
    nodeId: "osiris",
    publicName: "Osiris",
    nodeType: "agent",
    laneAffiliation: "audit",
    exposureState: "reviewed",
    authorityLayer: "human-review",
    summary: "Commercial structural-review and evidence lane for the Osiris Audit.",
    functionSummary: "Bounded intake, structural review, evidence pass, findings, recommendations, and delivery.",
    authoritySummary: "Findings and delivery only; no autonomous remediation, execution, or authority transfer.",
    relations: [{ label: "Produces", target: "evidence-linked audit findings", direction: "downstream" }],
    evidenceKind: "reviewed-copy",
    ctaMode: "view-path",
    ctaLabel: "Review audit lane",
    ctaHref: "#audit",
    color: "rose",
    position: "lower-right",
  },
  {
    id: "librarian",
    name: "Librarian",
    nodeId: "librarian",
    publicName: "Librarian",
    nodeType: "reference",
    exposureState: "deferred",
    authorityLayer: "canonical-reference",
    summary: "Knowledge-stewardship capability under reconciliation for artifact placement, retrieval, and source organization.",
    functionSummary: "Locates and organizes source artifacts without changing the authority of the source material.",
    authoritySummary: "Seat/node placement remains unresolved; retrieval and organization do not authorize source alteration or canon changes.",
    relations: [{ label: "Organizes", target: "source artifacts", direction: "related" }],
    evidenceKind: "snapshot",
    ctaMode: "none",
    color: "violet",
    position: "bottom",
  },
] as const satisfies readonly SurfaceNode[];
